# Generated by Django 4.1.2 on 2022-10-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas_collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vista',
            name='img',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
