# Generated by Django 4.1.2 on 2022-10-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vista',
            name='season',
            field=models.CharField(choices=[('WI', 'Winter'), ('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall')], default='SP', max_length=2),
        ),
    ]
