# Generated by Django 4.1.2 on 2022-10-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vistas_collector', '0002_vista_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250)),
                ('vista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistas_collector.vista')),
            ],
        ),
    ]
