# Generated by Django 4.1.2 on 2022-10-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas_collector', '0005_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
