# Generated by Django 4.1.2 on 2022-10-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas_collector', '0006_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='vista',
            name='tags',
            field=models.ManyToManyField(to='vistas_collector.tag'),
        ),
    ]
